# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast                  # Simply check whether the files parse as valid python
      - id: check-case-conflict        # Check for files that would conflict in case-insensitive filesystems
      - id: check-builtin-literals     # Require literal syntax when initializing empty or zero Python builtin types
      - id: check-docstring-first      # Checks a common error of defining a docstring after code
      - id: check-merge-conflict       # Check for files that contain merge conflict strings
      - id: check-toml                 # Attempts to load all TOML files to verify syntax
      - id: check-yaml                 # Attempts to load all YAML files to verify syntax
      - id: debug-statements           # Check for debugger imports and py37+ `breakpoint()` calls in python source
      - id: detect-private-key         # Detects the presence of private keys
      - id: end-of-file-fixer          # Ensures that a file is either empty, or ends with one newline
      - id: mixed-line-ending          # Replaces or checks mixed line ending
      - id: name-tests-test            # Check that test functions are named correctly
        args:
          - --pytest-test-first
      - id: trailing-whitespace        # This hook trims trailing whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      # run the linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: notebooks/
      # run the formatter
      - id: ruff-format
        exclude: notebooks/

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus
          - --keep-runtime-typing

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.32.1
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks: # https://github.com/python/mypy/issues/4008#issuecomment-582458665
      - id: mypy
        name: mypy
        pass_filenames: true
        args:
          [
            --strict,
            --ignore-missing-imports,
            --exclude=notebooks/,
          ]
        additional_dependencies: ["types-requests", "types-PyYAML"]
